<a href="https://colab.research.google.com/github/joy9808/2026-DA1/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [2]:
np.linspace(2,3,2)

array([2., 3.])

In [3]:
np.linspace(2,3,3)

array([2. , 2.5, 3. ])

In [5]:
np.linspace(2,3,3, retstep = True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [8]:
a = np.linspace(2,3,3, retstep = True)
float(a[1])

0.5

In [9]:
np.linspace(2,3,3, retstep = True, endpoint = False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

##numpy 주요 함수

###zeros()

In [10]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros((5, ), dtype = int)

array([0, 0, 0, 0, 0])

In [12]:
np.zeros((2, 3), dtype= int)

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros(2,3) #꼭 윗 코드처럼 쓸것

TypeError: Cannot interpret '3' as a data type

###ones()

In [15]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((2, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

###eye()

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [19]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###full()

In [20]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [21]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [22]:
np.full([2, 3], (1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [23]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [24]:
np.full([4, 3], fill_value = np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

###empty()

In [25]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [27]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [28]:
np.empty([2, 3], dtype = int)

array([[         1122344811,                   0, 7596458097932050547],
       [7957695015159097709, 2338042638583013491, 7305798796207024244]])

##배열과 스칼라와의 연산

In [29]:
a = np.arange(3)
a

array([0, 1, 2])

In [30]:
print (a + 2)
print (a - 2)
print (a * 2)
print (a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


#배열 슬라이싱과 형태 수정

In [33]:
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
print(a[3])
print(a[-2])

9
64


In [35]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [36]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


###역순과 대입

In [37]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [39]:
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [41]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

###2차원 배열의 첨자와 슬라이싱

In [42]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [44]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [45]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [48]:
a[-2, 3:]

array([21, 22, 23])

In [49]:
a[-2, 3:5]

array([21, 22])

In [50]:
a[-2]

array([18, 19, 20, 21, 22, 23])

In [51]:
[-2, ]

[-2]

In [52]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [54]:
a[, 1]

SyntaxError: invalid syntax (3063698125.py, line 1)

In [55]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [57]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [58]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [66]:
a[2, 4]

np.int64(16)

In [61]:
a[2][4]

np.int64(16)

In [62]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [67]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [68]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [71]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

##3차원 배열의 첨자와 슬라이싱

In [74]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
a[:, 0]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [79]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [80]:
a[:, 1, 1]

array([ 5, 17])

In [81]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [82]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [83]:
a[1, ..., 1]

array([13, 17, 21])

In [84]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a[1, 1, 1]

np.int64(17)

In [87]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [88]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###2차원 배열의 트랜스포즈 //중요


> 인용구 추가



In [89]:
a = np.arange(1,7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#브로드캐스팅

In [92]:
a = np.array([3, 4, 5])
b = np.array([8,7,6])
a + b

array([11, 11, 11])

In [93]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [95]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [97]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [99]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [100]:
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [102]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [103]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [104]:
x = arange(1, 4)
x

array([1, 2, 3])

In [105]:
y = arange(1,4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [106]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [107]:
x / y

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [108]:
x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [109]:
y = arange(1, 3)
y

array([1, 2])

In [110]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [111]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

##newaxis를 활용한 배열 차원 확장(증가)

In [113]:
from numpy import array
x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [114]:
np.newaxis is None

True

In [115]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [116]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [117]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [118]:
a.shape

(4, 1)

In [119]:
b = array([1,2,3])
b

array([1, 2, 3])

In [120]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [121]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

##고급 색인

In [122]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [124]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [125]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [126]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [127]:
print(x[[10, 11, 12,13]])

IndexError: index 10 is out of bounds for axis 0 with size 10

In [128]:
x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [129]:
x[0, 1]

np.int64(1)

In [130]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [131]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [136]:
x[..., 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [132]:
x[[0],[1]]

array([1])

In [137]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [135]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [138]:
x[[1, 3, 5]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [140]:
x[[1, 3, 5], : ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [141]:
x[[1, 3], [2, 2]] # == x[[1, 3], [2]]

array([10, 26])

In [142]:
x[[1, 3], [4, 2]]

array([12, 26])

In [139]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [143]:
x[[0, 2, 4], [1]]

array([ 1, 17, 33])

In [144]:
x[[0, 2, 4], 1]

array([ 1, 17, 33])

In [145]:
x[[0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [148]:
x[[0, 2, 4], [1,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [147]:
a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [149]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [151]:
a[[2,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [153]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [154]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [156]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [158]:
a[[2, 3]][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [159]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [160]:
a[arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [161]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [162]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [163]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [164]:
a[[2, 3, 4]][:, [-1, -2, -3, -4, -5, -6, -7]]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [166]:
a[[2, 3, 4]][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

#종료