<a href="https://colab.research.google.com/github/joy9808/2026-DA1/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#다차원 배열 결합과 분리

##vstack, hstack

In [2]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

In [3]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [10]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

##column_stack, row_stack

In [11]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [12]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [13]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [14]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [15]:
np.column_stack == np.hstack

False

In [16]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [18]:
np.row_stack((a, b))

/tmp/ipykernel_2918/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

##concatenate( (a, b), axis=None | 0 | 1 )

In [19]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [20]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [21]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [22]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [23]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [26]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [27]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [28]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [29]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [30]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

##stack(), stack( (arr_1, arr_2), axis = 0 | 1 | 2 )

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a
b

array([4, 5, 6])

In [32]:
a

array([1, 2, 3])

In [33]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
np.stack((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.stack((a, b), axis=-2)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.stack((a, b), axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

#3차원 배열

In [39]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [40]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [41]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [43]:
z = np.arange(20, 26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [44]:
ax0 = np.stack((x, y, z), axis = 0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [46]:
ax0.shape

(3, 2, 3)

In [47]:
ax1 = np.stack((x, y, z), axis = 1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [48]:
ax1.shape

(2, 3, 3)

In [49]:
ax2 = np.stack((x, y, z), axis = 2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [50]:
ax2.shape

(2, 3, 3)

In [54]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
c = np.array([1, 6, 2])
c

array([1, 6, 2])

In [57]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [55]:
np.hstack((a, np.expand_dims(c, axis = 1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  6],
       [ 9, 10, 11, 12,  2]])

In [56]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  6],
       [ 9, 10, 11, 12,  2]])

In [59]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [60]:
np.row_stack((a, b))

/tmp/ipykernel_2918/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [61]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [62]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [63]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [73]:
np.c_[x, y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
np.column_stack((x, y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
np.c_[x, 10, 20, y]

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [71]:
np.column_stack((x, 10, 20, y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

##np.r_[]

In [76]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [77]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [78]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [79]:
np.row_stack((a, b))

/tmp/ipykernel_2918/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [81]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [82]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [83]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [84]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [86]:
np.r_['0', a, a] #concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [87]:
np.r_['-1', a, a] #concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [88]:
np.r_['1', a, a] #concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

#배열 분리

##numpy.split(ary, indices_or_sections, axis = 0)

In [91]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [92]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [93]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [94]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [95]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [97]:
np.hsplit(a, 3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [98]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [99]:
np.split(a, 3, axis = 1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [100]:
np.split(a, 4, axis = 1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [101]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [102]:
np.split(b, 3, axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [103]:
np.split(b, [2, 4, 6], axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [105]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [106]:
np.split(a, [3, 5, 7], axis = 1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [107]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
np.split(b, 3, axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [109]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [111]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [112]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [113]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [114]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [116]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [117]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [118]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [119]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [120]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [121]:
a[:1, :]

array([[0, 1, 2]])

In [122]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [123]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [124]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [125]:
np.split(x, 2, axis = 0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [126]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [127]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [128]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [129]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [130]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [131]:
np.vsplit(x, [1,3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [132]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [133]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [134]:
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [135]:
np.hsplit(x, [1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

#numpy 난수와 다양한 함수

###난수 생성기
###numpy.Random.default_rng

In [171]:
import numpy as np

rg = np.random.default_rng(12345)
rg.random() # [0~1사이의 실수]

0.5118216247002567

In [172]:
r = rg.random()
r

0.9504636963259353

In [138]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [139]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [177]:
rg = np.random.default_rng(12345)
r = rg.integers(low = 0, high = 10, size = 3)
r

array([6, 2, 7])

In [175]:
rg.integers(1, 7, (3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [182]:
rg = np.random.default_rng(1)
rg.standard_normal(3) # 표준 정규분포 실수 난수

array([0.34558419, 0.82161814, 0.33043708])

In [196]:
rg.standard_normal((3, 4)) # 표준 정규분포 실수 난수

array([[-1.56693315e-03,  8.99566417e-01, -2.36663322e-01,
        -6.29354924e-01],
       [ 2.31511064e-01,  7.00151751e-01,  6.63657571e-01,
         1.97247385e+00],
       [ 2.09167472e-01, -5.92410100e-01, -1.25979190e-01,
        -7.24985456e-02]])

In [190]:
rg.standard_normal((4, 3))

array([[-1.04879657e-03,  4.45573554e-01,  4.68404336e-01],
       [ 8.76242196e-01,  2.56485627e-01, -9.48283390e-02],
       [-2.58848065e-01,  1.05574280e+00, -2.25085428e+00],
       [-1.38655325e-01,  3.30001040e-02, -1.42534896e+00]])

##배열 결합 연습

In [197]:
a = np.arange(1, 4) #shift + alt + 아래 화살표 == 코드 복사
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [198]:
p = np.arange(1, 7).reshape(2, 3) #shift + alt + 아래 화살표 == 코드 복사
q = np.arange(11, 17).reshape(2,3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [199]:
np.vstack((a, b, c)) # 10 -> 20

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [200]:
np.vstack((p, q, r)) # 20 -> 20

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [201]:
np.hstack((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
np.hstack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [204]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [205]:
np.column_stack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [208]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
np.concatenate((a, b, c), axis = 0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
np.concatenate((a, b, c), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
np.concatenate((a, b, c), axis = -1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [214]:
np.concatenate((p, q, r), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [215]:
np.concatenate((p, q, r), axis = 1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [216]:
np.concatenate((p, q, r), axis = None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [217]:
np.c_[a, b, c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [218]:
np.c_[p, q, r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [219]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [220]:
np.column_stack([a, b, c])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [222]:
np.r_[a, b, c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [224]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])